### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by sanders41**
# Purpose

Keep dependencies up to date.

# Changes
- Add a dependabot.yaml file

# Checklist
- [x] Update [`CHANGELOG.md`](https://github.com/ethyca/fidesops/blob/main/CHANGELOG.md) file
  - [x] Merge in main so the most recent `CHANGELOG.md` file is being appended to
  - [x] Add description within the `Unreleased` section in an appropriate category. Add a new category from the list at the top of the file if the needed one isn't already there.
  - [x] Add a link to this PR at the end of the description with the PR number as the text. example: [#1](https://github.com/ethyca/fidesops/pull/1)
- [ ] Applicable documentation updated (guides, quickstart, postman collections, tutorial, fidesdemo, [database diagram](https://github.com/ethyca/fidesops/blob/main/docs/fidesops/docs/development/update_erd_diagram.md).
- If docs updated (select one):
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
- [ ] Good unit test/integration test coverage
- [ ] This PR contains a DB migration. If checked, the reviewer should confirm with the author that the [down_revision correctly references the previous migration](https://ethyca.github.io/fidesops/development/contributing_details/#alembic-migrations) before merging
- [ ] The `Run Unsafe PR Checks` label has been applied, and checks have passed, if this PR touches any external services

# Ticket

Fixes #

### CODE REVIEW

**Comment by TheAndrewJackson** [comment]
@sanders41 Everything looks good to me but I'm not sure how to validate that the yaml file works as expected since it runs once a week. Do you know if there is a way to do that?

**Comment by sanders41** [comment]
We can manually run it at any time, but not until the yaml file is in place. It is basically like the workflow files, no way to test first. The good news is it just opens PRs so if anything is wrong we can close the PR and try again so no harm done.

**Comment by sanders41** [comment]
I fixed the conflict.

**Review by TheAndrewJackson — APPROVED** [review]

**Comment by daveqnet** [comment]
@sanders41 & @TheAndrewJackson, let me know how you get on with the volume of Dependabot auto-PRs in this repo when it's configured for [version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates).

My experience of it is that it's _very_ noisy, especially in repos with npm manifest files, creating one PR per dependency bump per manifest file.

From a security perspective there's no issue if the PRs keep getting reviewed and merged, but I'd be slightly concerned about PR fatigue in the fidesops team, resulting in a security update being missed.

An alternative could be to just configure it for [security updates](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) or even just fall back to [alerts](https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts).

The levels of Dependabot go something like:

1. Dependency graph enabled
2. Dependabot alerts enabled
3. Dependabot security updates enabled
4. Dependabout version updates enabled
5. Dependabot PRs auto-merged without human review

I'm happy with just alerts enable for most repos. Anyway, please let me know how it goes.

**Pull request merged**
