### PR TITLE
updating images for docs site

### PR DESCRIPTION
**Pull request by iamkelllly**
# Purpose
Standardized styling of diagrams and updated reference to png

# Changes
- [ ] Updated 5 images
- [ ] removed Deployment diagram svg file, swapped for png instead and updated reference

# Checklist

- [ ] Applicable documentation updated (guides, quickstart, postman collections, tutorial, fidesdemo, [database diagram](https://github.com/ethyca/fidesops/blob/main/docs/fidesops/docs/development/update_erd_diagram.md))
- [ ] Good unit test/integration test coverage
- [ ] This PR contains a DB migration. If checked, the reviewer should confirm with the author that the [down_revision correctly references the previous migration](https://ethyca.github.io/fidesops/development/contributing_details/#alembic-migrations) before merging
- [ ] The `Run Unsafe PR Checks` label has been applied, and checks have passed, if this PR touches any external services

# Ticket
no ticket

### CODE REVIEW

**Review by pattisdr — CHANGES_REQUESTED** [review]
ah found some typos -

Deployment_Diagram - 
Elasticache, and FidesOps, I thought we were going with a lowercase "o", also "fidesops Web Server" at top, that might be an opportunity to capitalize Fidesops

Traversal graph -
Purchase misspelled

Traversal tables
identity misspelled

**Comment by iamkelllly** [comment]
thanks @pattisdr i'm updating the branch today!

**Review by pattisdr — APPROVED** [review]
Verified my request and Sean's requests, looks great @iamkelllly

**Comment by pattisdr** [comment]
Ah, I can't merge until @seanpreston approves

**Comment by pattisdr** [comment]
🎉

**Pull request merged**
